### ISSUE TITLE
Changes to prettier rules do not apply

### ISSUE THREAD

**Issue by onesine** [adonisjs/eslint-config#4]
### Package version

2.0.0-beta.6

### Describe the bug

I'm currently experiencing a problem with `Adonisjs` version 6. It seems that the `@adonisjs/eslint-config` package is used for `prettier` and `eslint` configs. I've modified the prettier configuration as follows.

```javascript
import { configApp } from "@adonisjs/eslint-config";
import eslintPluginImport from "eslint-plugin-import";

export default configApp({
    name: "Custom config",
    plugins: {
        import: eslintPluginImport
    },
    rules: {
        "prettier/prettier": [
            "error",
            {
                semi: true,
                singleQuote: false,
                tabWidth: 4,
                printWidth: 100,
                trailingComma: "none"
            }
        ],
        "import/order": [
            "error",
            {
                "alphabetize": {
                    order: "asc",
                    caseInsensitive: true
                },
                "newlines-between": "always"
            }
        ]
    }
});
```
After this modification, I have the `prettier` error.

<img width="1066" alt="Capture d’écran 2024-10-14 à 13 07 21" src="https://github.com/user-attachments/assets/54429237-2dbd-4e17-ad66-a787cc5f8369">

But when I run the command `npm run format` the corrections don't apply.

**Comment by Julien-R44** [comment]
Look at your `package.json`. Your prettier config is in there: 

```jsonc
{
  // ...
  "prettier": "@adonisjs/prettier-config",
}
```

That's what you need to change

**Comment by onesine** [comment]
Thanks for the quick response
